### ISSUE TITLE
Estimating gene types

### ISSUE THREAD

**Issue by lazappi** [kieranrcampbell/phenopath#8]
Hi

I am working on add your PhenoPath simulation to my Splatter simulation package. Thanks for providing the function, that made it really easy to implement.

I was just wondering if you have a suggested method for deciding on the number of each gene type to simulate based on a counts matrix of real data? At the moment I am just evenly dividing up the total number of genes. I am happy to leave it at that but just thought I would check if there is something else you suggest.

Thanks

**Comment by kieranrcampbell** [comment]
Hi Luke,

Thanks for your message.

I think evenly is a pretty good way of doing it. The `sample_pst_beta` is probably the most unlikely situation, though interestingly the top interacting gene from the Shalek dataset does precisely that.

Also, one of the reviewer comments was that our simulated data we test on shouldn't be from the model, so we now have code for sigmoidally-regulated interactions that looks like this:

<img width="917" alt="screen shot 2017-10-04 at 10 53 33" src="https://user-images.githubusercontent.com/2039489/31170005-6dad0de4-a8f2-11e7-96df-1953f74f8da6.png">

which would represent logged expression. Happy to forward on code if you'd find it useful.

Cheers,

Kieran

**Comment by lazappi** [comment]
Great, thanks. I am basically just writing a wrapper around `simulate_phenopath` so I will stick with that that does. While I am asking questions I noticed that this function returns continuous values rather than counts, is this an approximation of log expression?

**Comment by kieranrcampbell** [comment]
Yes designed to simulated `log2(counts + 1)`, so `round(2^x - 1)` should give you counts.
